#' Euler 40
#'
#' Finds the product certain digits of the irrational number that is generated by
#' pasteing 1,2,3,4.... together, resulting in the value 0.1234...
#'
#' @return Integer value
#' @export
euler40 <- function() {
	# Generate a million values as a string object
	text <- paste(1:(10^6), collapse = "")

	# Values we are interested in
	index <- c(1,10,10^(1:6))

	# The result we will append to
	result <- c()

	for(i in index){
		# Select all of the values we care about, converting it to numeric values
		result <- append(result,as.numeric(substring(text,i,i)))
	}

	# Produce the product of the result
	prod(result)
}

